services:
  postgres:
    image: postgres:13.7
    container_name: spring-batch-playground-postgres
    ports:
      - 5432:5432
    # if you want to persist data
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: 1qazxsw2
      POSTGRES_DB: spring-batch
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
